version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/New_York
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production
    labels:
      - dependencies
      - javascript
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "10:00"
      timezone: America/New_York
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci
